/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MandovaAmbulanceWlList {
    }
}
declare global {
    interface HTMLMandovaAmbulanceWlListElement extends Components.MandovaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMandovaAmbulanceWlListElement: {
        prototype: HTMLMandovaAmbulanceWlListElement;
        new (): HTMLMandovaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "mandova-ambulance-wl-list": HTMLMandovaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MandovaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "mandova-ambulance-wl-list": MandovaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mandova-ambulance-wl-list": LocalJSX.MandovaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMandovaAmbulanceWlListElement>;
        }
    }
}
